### ISSUE TITLE
Update Read me file 

### ISSUE THREAD

**Issue by Varda003** [Ash515/AutomaDesk#10]
As mentioned in GSSOC'24 all the features are needed to be explained for more understanding. I am well experienced in creating documentation please assign this issue to me.

**Comment by hasmithagunda123** [comment]
Please assign this task to me

**Comment by Lumiere-MULAGWA** [comment]
Please assign me a tasks

**Comment by akhundubedullah** [comment]
I have experience writing Readme files for various projects, and I'm eager to apply that knowledge to create an excellent Readme file that meets the requirements of GSSoC. Please assign me this task with GSSOC'24 tag.Thanks

**Comment by akshatsharma2407** [comment]
Hello, I am fully capable of updating your README section as a GSSoC contributor. Kindly assign me this issue as I possess intermediate knowledge of the technology utilized in your project. I am confident that I am the best fit for this task.

**Comment by aryasd29** [comment]
Hey! I have worked on projects and am good with readme files please assign this issue to me. I am certain that I am the most suitable candidate for this task.

**Comment by bubblepreetkaur06** [comment]
Kindly assign me this task
