### ISSUE TITLE
Add Single File Renaming Functionality 

### ISSUE THREAD

**Issue by akhundubedullah** [Ash515/AutomaDesk#13]
I propose adding a feature to the file organizer tool that allows users to easily rename individual files. This feature would include:

GUI Integration: A user-friendly interface (built with Tkinter) for selecting a file and entering a new name.

Renaming Logic: Implementation of the actual file renaming process using Python's os.rename function.

Error Handling: Checks to ensure the new name is valid and doesn't conflict with existing files.

Confirmation: A step to confirm the renaming before it's permanently applied.

I propose adding a feature to the file organizer tool that allows users to easily rename individual files. This feature would include:

GUI Integration: A user-friendly interface (built with Tkinter) for selecting a file and entering a new name.
Renaming Logic: Implementation of the actual file renaming process using Python's os.rename function.
Error Handling: Checks to ensure the new name is valid and doesn't conflict with existing files.
Confirmation: A step to confirm the renaming before it's permanently applied.

**Comment by thakurboy004** [comment]
I would like to work on this issue please assign this to me

**Comment by mvp-2003** [comment]
I have a question regarding this: I am unable to quite think of a possible use case, because a file/folder rename option is already available in File Manager/Windows Explorer. Will this be a good integration?

**Comment by bhavikmenaria** [comment]
To add single file renaming functionality, you could implement a method that allows users to rename individual files directly within the GUI. This feature would provide users with the flexibility to rename files without relying solely on predefined rules.
