### ISSUE TITLE
Hi contributing in this project

### ISSUE THREAD

**Issue by Chelseasingla1** [Ash515/AutomaDesk#24]
hi can you please provide guidelines how can i contribute in this project

**Comment by Ash515** [comment]
Hi, @Chelseasingla1 kindly create automation services based on GUI for file organization techniques using Python.

**Comment by Chelseasingla1** [comment]
> Hi, @Chelseasingla1 kindly create automation services based on GUI for file organization techniques using Python.

Okay so should i create a new issue based on that?
